name       : perl-sort-key
version    : 1.33
release    : 8
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SA/SALVA/Sort-Key-1.33.tar.gz : ed6a4ccfab094c9cd164f564024e98bd21d94f4312ccac4d6246d22b34081acf
license    : Artistic-2.0
component  : programming.perl
summary    : The fastest way to sort anything in Perl
description: |
    The fastest way to sort anything in Perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
